config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  devise_for :users, :controllers => {
  :sessions => 'users/sessions'
  }
  devise_scope :user do
    get 'login' => 'devise/sessions#new'
    post 'login' => 'devise/sessions#create'
    delete 'destroy' => 'devise/sessions#destroy',as: :current_user_destroy
  end

  resources :signup ,only: [:index, :create] do
    collection do
      get 'registration'
      post 'registration' => 'signup#first_validation'
      get 'sms_authentication'
      post 'sms_authentication' => 'signup#sms_check'
      get 'address'
      post 'address' => 'signup#second_validation'
      get 'done'
    end
  end

  root 'posts#index'

  resources :posts do
    resources :messages, only: [:new, :create]
  end


end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  before_action :redirect_to_index_from_sms,only: :sms_authentication
  before_action :redirect_to_index_from_address,only: :address

  def index
  end

  def registration
    @user = User.new
    @profile = Profile.new
  end

  def first_validation
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:birthyear] = profile_params[:birthyear]
    session[:birthmonth] = profile_params[:birthmonth]
    session[:birthday] = profile_params[:birthday]
    session[:family_name] = profile_params[:family_name]
    session[:personal_name] = profile_params[:personal_name]
    session[:family_name_kana] = profile_params[:family_name_kana]
    session[:personal_name_kana] = profile_params[:personal_name_kana]
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation]
    )
    @profile = Profile.new(
      user: @user,
      birthyear: session[:birthyear],
      birthmonth: session[:birthmonth],
      birthday: session[:birthday],
      family_name: session[:family_name],
      personal_name: session[:personal_name],
      family_name_kana: session[:family_name_kana],
      personal_name_kana: session[:personal_name_kana],
      prefecture_id: '1',
      city: '那覇市',
      postal_code: '888-8888',
      tel: '090-1234-5678',
      house_code: '99',
      bulid_name: '首里城'
    )
    check_user_valid = @user.valid?
    check_profile_valid = @profile.valid?
    unless check_user_valid && check_profile_valid
      render 'signup/registration'
    else
      session[:through_first_valid] = "through_first_valid"
      redirect_to sms_authentication_signup_index_path
    end
  end

  def sms_authentication
    @profile = Profile.new
  end

  def sms_check
    session[:tel] = profile_params[:tel]
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation]
    )
    @profile = Profile.new(
      user: @user,
      birthyear: session[:birthyear],
      birthmonth: session[:birthmonth],
      birthday: session[:birthday],
      family_name: session[:family_name],
      personal_name: session[:personal_name],
      family_name_kana: session[:family_name_kana],
      personal_name_kana: session[:personal_name_kana],
      prefecture_id: '1',
      city: '那覇市',
      postal_code: '888-8888',
      tel: session[:tel],
      house_code: '99',
      bulid_name: '首里城'
    )
    check_user_valid = @user.valid?
    check_profile_valid = @profile.valid?
    unless check_user_valid && check_profile_valid
      render 'signup/sms_authentication'
    else
      session[:through_sms_check] = "through_sms_check"
      redirect_to address_signup_index_path
    end
  end

  def address
    @profile = Profile.new
  end

  def second_validation
    session[:postal_code] = profile_params[:postal_code]
    session[:prefecture_id] = profile_params[:prefecture_id]
    session[:city] = profile_params[:city]
    session[:house_code] = profile_params[:house_code]
    session[:bulid_name] = profile_params[:bulid_name]
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation]
    )
    @user.save
    @profile = Profile.new(
      user: @user,
      birthyear: session[:birthyear],
      birthmonth: session[:birthmonth],
      birthday: session[:birthday],
      family_name: session[:family_name],
      personal_name: session[:personal_name],
      family_name_kana: session[:family_name_kana],
      personal_name_kana: session[:personal_name_kana],
      prefecture_id: session[:prefecture_id],
      city: session[:city],
      postal_code: session[:postal_code],
      tel: session[:tel],
      house_code: session[:house_code],
      bulid_name: session[:bulid_name]
    )
    if @profile.save
      reset_session
      session[:id] = @user.id
      redirect_to done_signup_index_path
      return 
    else
      reset_session
      render :address
    end
  end

  def done
    unless session[:id]
      redirect_to signup_index_path 
      return
    end
    sign_in User.find(session[:id])
  end

  private

  def user_params
    params.require(:user).permit(:nickname,:email,:password,:password_confirmation)
  end

  def profile_params
    params.require(:profile).permit(:birthyear,:birthmonth,:birthday,:family_name,:personal_name,:family_name_kana,:personal_name_kana,:postal_code,:prefecture_id,:city,:tel,:house_code,:bulid_name)
  end

  def redirect_to_index_from_sms
    redirect_to signup_index_path unless session[:through_first_valid].present? && session[:through_first_valid] == "through_first_valid"
  end

  def redirect_to_index_from_address
    redirect_to signup_index_path unless session[:through_sms_check].present? && session[:through_sms_check] == "through_sms_check"
  end

end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/address.html.haml
.user-datail
  = form_for @profile, url: address_signup_index_path,method: :post do |f|
    .user-datail-head
      %h2 住所入力
    .user-datail-text-address
      .user-datail-form  
        = f.label :postal_code, "郵便番号"
        %span.form-required
          必須
      = f.text_field :postal_code, placeholder:"例）１２３４５６７"

      .user-datail-form 
        = f.label :prefecture_id, "都道府県"
        %span.form-required
          必須
      = f.collection_select :prefecture_id, Prefecture.all, :id, :name
      
      .user-datail-form 
        = f.label :city, "市区町村"
        %span.form-required
          必須
      = f.text_field :city, placeholder:"例）横浜市緑区"
      .user-datail-form 
        = f.label :house_code, "番地"
        %span.form-required
          必須
      = f.text_field :house_code, placeholder:"例）青山1-1-1"
      .user-datail-form 
        = f.label :bulid_name, "建物名"
        %p.from-arbitrary
          任意
      = f.text_field :bulid_name, placeholder:"例）柳ビル103"

      = f.submit '次へ進む', class:"user-datail-form__btn"

app/views/signup/done.html.haml
.main-container4
  .header4
    %h2 会員登録完了
  .main-contents4
    .comment
      %span ありがとうございます。
      %br 会員登録が完了しました。
      = link_to root_path, data: {"turbolinks" => false}, class:"comment__start-btn" do
        interactionをはじめる

app/views/signup/index.html.haml
.contents-sns__main__btn  
  .contents-sns__main__btn__link
  = link_to registration_signup_index_path, class: "contents-sns__main__btn__link__email" do
    = icon('far', 'envelope',class:"contents-sns__main__btn__link__email__icon-mail")
    %span
      メールアドレスで登録する

app/views/signup/registration.html.haml
- content_for(:html_title) {'会員情報入力'}
/= render partial: 'signup-header1'
.signup-container
  %h2.signup-header 会員情報入力
  .registration-form

    = form_for @user, url: registration_signup_index_path,method: :post do |f|
      .signup-form-container.registration-form__first-container
        .signup-form-container__title
          = label :nickname, 'ニックネーム', class: 'signup-label'
        = f.text_field :nickname, placeholder: '例）メルカリ太郎'
      .signup-form-container
        .signup-form-container__title
          = label :email, 'メールアドレス'
        = f.text_field :email, placeholder: 'PC・携帯どちらでも可'
      .signup-form-container
        .signup-form-container__title
          = label :password, 'パスワード'
        = f.password_field :password,placeholder: '７文字以上'
      .signup-form-container
        .signup-form-container__title
          = label :password_confirmation, 'パスワード（確認）'
        = f.password_field :password_confirmation, placeholder: '7文字以上'

      //今回はprofileにも同時に値を送りたいのでfields_forを使っています。
      = fields_for @profile,url: registration_signup_index_path,method: :post do |p|
        .signup-form-container
          .signup-form-container__title
            = label :name, 'お名前(全角)', class: 'signup-label'
          .signup-form-container__name
            = p.text_field :family_name, placeholder: '例）山田'
            = p.text_field :personal_name, placeholder: '例）彩'
          .signup-form-container__name
            = p.text_field :family_name_kana, placeholder: '例）ヤマダ'
            = p.text_field :personal_name_kana, placeholder: '例）アヤ'  
        .l-regist-wholeform__mainform__input__info__birthday
          = p.label :birthday, "生年月日"
          %span.form-require 必須
          %br/
          .l-regist-wholeform__mainform__input__info__birthday__select
            .l-regist-wholeform__mainform__input__info__birthday__select__year
              = p.select :birthyear,[["--", ""],
                                ["2012", 2012],
                                ["2011", 2011],
                                ["2010", 2010],
                                ["2009", 2009],
                                ["2008", 2008],
                                ["2007", 2007],
                                ["2006", 2006],
                                ["2005", 2005],
                                ["2004", 2004],
                                ["2003", 2003],
                                ["2002", 2002],
                                ["2001", 2001],
                                ["2000", 2000],
                                ["1999", 1999],
                                ["1998", 1998],
                                ["1997", 1997],
                                ["1996", 1996],
                                ["1995", 1995],
                                ["1994", 1994],
                                ["1993", 1993],
                                ["1992", 1992],
                                ["1991", 1991],
                                ["1990", 1990],
                                ["1989", 1989],
                                ["1988", 1988],
                                ]
              %span 
              年
            .l-regist-wholeform__mainform__input__info__birthday__select__month
              = p.select :birthmonth,[["--", ""],
                              ["1", 1],
                              ["2", 2],
                              ["3", 3],
                              ["4", 4],
                              ["5", 5],
                              ["6", 6],
                              ["7", 7],
                              ["8", 8],
                              ["9", 9],
                              ["10", 10],
                              ["11", 11],
                              ["12", 12],
                              ]
              %span
              月
            .l-regist-wholeform__mainform__input__info__birthday__select__day
              = p.select :birthday,[["--", ""],
                              ["1", 1],
                              ["2", 2],
                              ["3", 3],
                              ["4", 4],
                              ["5", 5],
                              ["6", 6],
                              ["7", 7],
                              ["8", 8],
                              ["9", 9],
                              ["10", 10],
                              ["11", 11],
                              ["12", 12],
                              ["13", 13],
                              ["14", 14],
                              ["15", 15],
                              ["16", 16],
                              ["17", 17],
                              ["18", 18],
                              ["19", 19],
                              ["20", 20],
                              ["21", 21],
                              ["22", 22],
                              ["23", 23],
                              ["24", 24],
                              ["25", 25],
                              ["26", 26],
                              ["27", 27],
                              ["28", 28],
                              ["29", 29],
                              ["30", 30],
                              ["31", 31],
                              ]
              %span
              日 
      = f.submit '次へ進む'

app/views/signup/sms_authentication.html.haml
= form_for @profile, url: sms_authentication_signup_index_path,method: :post do |f|
  = label :nickname, '携帯電話の番号'
  = f.text_field :tel, placeholder: '携帯電話の番号を入力'
  = f.submit 'SMSを送信する'