config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  devise_for :users, :controllers => {
  :sessions => 'users/sessions'
  }
  devise_scope :user do
    get 'login' => 'devise/sessions#new'
    post 'login' => 'devise/sessions#create'
    delete 'destroy' => 'devise/sessions#destroy',as: :current_user_destroy
  end

  resources :signup ,only: [:index, :create] do
    collection do
      get 'registration'
      post 'registration' => 'signup#first_validation'
      get 'sms_authentication'
      post 'sms_authentication' => 'signup#sms_check'
      get 'address'
      post 'address' => 'signup#second_validation'
      get 'done'
    end
  end

  root 'posts#index'

  resources :posts do
    resources :messages, only: [:new, :create]
  end


end

app/models/post.rb
class Post < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user
  has_many :images
  has_many :messages
  accepts_nested_attributes_for :images, allow_destroy: true
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  PER = 6

  def index
    @posts = Post.includes(:images).order('created_at DESC')
    @posts = Post.page(params[:page]).per(6).order('created_at DESC')
  end

  def new
    @post = Post.new
    @post.images.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @posts = Post.find(params[:id])
    @image = Image.find(params[:id])
    # @messages = @post.messages.includes(:user_id)
  end

  

  private
  
  def post_params
    params.require(:post).permit(:title, :detail, :prefecture_id, :city, :house_code, :build_name, images_attributes: [:image, :id]).merge(user_id:current_user.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_top.html.haml
- if user_signed_in?
  .content
    .content__main
      .content__main__text
        新着一覧
      .content__main__unit
        - @posts.each do |post|
          .content__main__unit__image
            = link_to post_path(post.id) do
              - if post.images.empty?
                画像がありません
              - else
                = image_tag post.images[0].image.to_s
              %br= post.title
        = paginate @posts
- else
  .cont
    .cont_principal
      .cont_text_img
        .cont_img_back
          %img.img_1{:alt => "", :src => "https://i.imgur.com/yQErMlN.jpg"}/
          %img.img_2{:alt => "", :src => "https://i.imgur.com/J6FwYUM.jpg"}/
        .cont_text
          %h1 Interaction
          %p 地方では、中小企業の休廃業・解散が相次げば、それが地域の経済や雇用に多大な影響を及ぼす可能性も考えられています。こうした事情から、事業承継や後継者問題は社会問題として広く認知されるようになりました。
          %p 当サイトではこうした事業継承の手助けができればと思っております。
        .cont_img_frond
          %img.img_1{:alt => "", :src => "https://i.imgur.com/yQErMlN.jpg"}/
          %img.img_2{:alt => "", :src => "https://i.imgur.com/J6FwYUM.jpg"}/
        

app/views/posts/index.html.haml
.wrapper
  = render "/layouts/header"
  = render "top"

app/views/posts/new.html.haml
.main
  %selection.main__block
    = form_with model:@post, local:true do |f|
      %h2.post-block
        投稿内容を入力
      .post-form
        .post-form__upload
          %h3.post-form__upload__image
            画像
            %span.require 必須
          %p 最大10枚までアップロードできます
          #image-box-1
            .item-num-0#image-box__container
              = f.fields_for :images do |i|
                .input-area
                  %label{for: "img-file"}
                    = i.file_field :image, type: 'file', name: "post[images_attributes][][image]",style: "display:none", value:"", id:"img-file"
                    %i.fas.fa-camera

        .post-form__title
          %h3.post-form__title__text
            タイトル
            %span.require 必須
          %br
          = f.text_field :title, placeholder:"タイトル名(必須)"

        .post-form__title
          %h3.post-form__title__text
            詳しい内容
            %span.require 必須
          %br
          = f.text_area :detail,size: "85x15", placeholder:"詳しい内容(必須)"

        .post-form__title
          %h3.post-form__title__text
            都道府県
            %span.require 必須
          %br
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name

        .post-form__title
          %h3.post-form__title__text
            市区町村
            %span.require 必須
          %br
          = f.text_field :city, placeholder:"例）横浜市緑区"

        .post-form__title
          %h3.post-form__title__text
            番地
            %span
          %br
          = f.text_field :house_code, placeholder:"例）青山1-1-1"

        .post-form__title
          %h3.post-form__title__text
            建物名
            %span
          %br
          = f.text_field :build_name, placeholder:"例）柳ビル103"

        .post-form__btn
          = f.submit "Post", class: "post-form__btn__red"
          %span 投稿する

app/views/posts/show.html.haml
.main
  %selection.main-show
    %h2.post-show
      = @posts.title
    .show-form
      .show-form__upload
        = image_tag @image.image.to_s

      .show-form__title
        .show-form__title__text 
          詳しい内容
        .show-form__title__detail
        = @posts.detail

      .show-form__title
        .show-form__title__text 
          都道府県
        .show-form__title__prefecture
          = @posts.prefecture.name

      .show-form__title
        .show-form__title__text
          市区町村
        .show-form__title__city
          = @posts.city

      .show-form__title
        .show-form__title__text
          番地
        .show-form__title__house
          = @posts.house_code

      .show-form__title
        .show-form__title__text
          建物名
        .show-form__title__build
          = @posts.build_name

      .show-form__title
        .show-form__title__text
          = link_to 'メッセージを送る', new_post_message_path(@posts.id)