config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :all
  devise_for :users, :controllers => {
  :sessions => 'users/sessions'
  }
  devise_scope :user do
    get 'login' => 'devise/sessions#new'
    post 'login' => 'devise/sessions#create'
    delete 'destroy' => 'devise/sessions#destroy',as: :current_user_destroy
  end

  resources :signup ,only: [:index, :create] do
    collection do
      get 'registration'
      post 'registration' => 'signup#first_validation'
      get 'sms_authentication'
      post 'sms_authentication' => 'signup#sms_check'
      get 'address'
      post 'address' => 'signup#second_validation'
      get 'done'
    end
  end

  root 'posts#index'

  resources :posts do
    resources :messages, only: [:new, :create]
  end


end

app/views/layouts/_header.html.haml
%header
  - if user_signed_in?
    .header-inner
      .header-inner__logo
        Interaction
      .header-inner__search
        = form_for to_s do |f|
          = f.search_field :title, placeholder:"何かお探しですか？", id:"field"
          = f.button icon("fa", "search", class:"icon"), class:"btn"
    .header-list
      .header-list__right
        .container
          %a.bnt-massage{:href => "/signup"}
            Mypage
            %span マイページ
          %a.bnt-massage{:href => "/posts/new"}
            Post
            %span 投稿する
          = link_to current_user_destroy_path, class: "bnt-massage", method: :delete do
            Logout
            %span ログアウト
            
            -# ログイン状態

  - else
    .header-inner
      .header-inner__logo
        Interaction
      .header-list
        .header-list__right
          .container
          %a.bnt-massage{:href => "/signup"}
            Signup
            %span 新規会員登録

          .container
          %a.bnt-massage{:href => "/users/sign_in"}
            Login
            %span ログイン
          -#   -# ログアウト状態

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title InteractionApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield